//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PezeshkPlus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PezeshkPlusEntities : DbContext
    {
        public PezeshkPlusEntities()
            : base("name=PezeshkPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int USP_INS_Admin(string firstName, string lastName, string email, string password, string phoneNumber, string nationalID, Nullable<bool> type)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_Admin", firstNameParameter, lastNameParameter, emailParameter, passwordParameter, phoneNumberParameter, nationalIDParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> USP_SEL_AdminType(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("USP_SEL_AdminType", emailParameter);
        }
    
        public virtual int USP_DEL_Article(Nullable<int> articleID)
        {
            var articleIDParameter = articleID.HasValue ?
                new ObjectParameter("articleID", articleID) :
                new ObjectParameter("articleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_DEL_Article", articleIDParameter);
        }
    
        public virtual int USP_INS_Article(string topic, string text, string writerName, string picAddress)
        {
            var topicParameter = topic != null ?
                new ObjectParameter("topic", topic) :
                new ObjectParameter("topic", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var writerNameParameter = writerName != null ?
                new ObjectParameter("writerName", writerName) :
                new ObjectParameter("writerName", typeof(string));
    
            var picAddressParameter = picAddress != null ?
                new ObjectParameter("picAddress", picAddress) :
                new ObjectParameter("picAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_Article", topicParameter, textParameter, writerNameParameter, picAddressParameter);
        }
    
        public virtual ObjectResult<USP_SEL_Article_Result> USP_SEL_Article(Nullable<int> articleID)
        {
            var articleIDParameter = articleID.HasValue ?
                new ObjectParameter("articleID", articleID) :
                new ObjectParameter("articleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_Article_Result>("USP_SEL_Article", articleIDParameter);
        }
    
        public virtual ObjectResult<USP_SEL_Articles_Result> USP_SEL_Articles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_Articles_Result>("USP_SEL_Articles");
        }
    
        public virtual ObjectResult<USP_SEL_Top3Articles_Result> USP_SEL_Top3Articles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_Top3Articles_Result>("USP_SEL_Top3Articles");
        }
    
        public virtual int USP_DEL_Comment(Nullable<int> commentID)
        {
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("commentID", commentID) :
                new ObjectParameter("commentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_DEL_Comment", commentIDParameter);
        }
    
        public virtual int USP_DEL_Doctor(Nullable<int> doctorID)
        {
            var doctorIDParameter = doctorID.HasValue ?
                new ObjectParameter("doctorID", doctorID) :
                new ObjectParameter("doctorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_DEL_Doctor", doctorIDParameter);
        }
    
        public virtual int USP_DEL_DoctorMedicalField(string email, string medicalFieldName)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var medicalFieldNameParameter = medicalFieldName != null ?
                new ObjectParameter("medicalFieldName", medicalFieldName) :
                new ObjectParameter("medicalFieldName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_DEL_DoctorMedicalField", emailParameter, medicalFieldNameParameter);
        }
    
        public virtual int USP_INS_AddMedicalField(string email, Nullable<int> medicalFieldID)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var medicalFieldIDParameter = medicalFieldID.HasValue ?
                new ObjectParameter("medicalFieldID", medicalFieldID) :
                new ObjectParameter("medicalFieldID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_AddMedicalField", emailParameter, medicalFieldIDParameter);
        }
    
        public virtual int USP_INS_Comment(string email, string text, string writerName, Nullable<int> replyID)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var writerNameParameter = writerName != null ?
                new ObjectParameter("writerName", writerName) :
                new ObjectParameter("writerName", typeof(string));
    
            var replyIDParameter = replyID.HasValue ?
                new ObjectParameter("replyID", replyID) :
                new ObjectParameter("replyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_Comment", emailParameter, textParameter, writerNameParameter, replyIDParameter);
        }
    
        public virtual int USP_INS_Doctor(string firstName, string lastName, string email, string password, string phoneNumber, string province, string city, Nullable<int> medicalFieldID, string nationalID, string clinicPhone, string address)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("province", province) :
                new ObjectParameter("province", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var medicalFieldIDParameter = medicalFieldID.HasValue ?
                new ObjectParameter("medicalFieldID", medicalFieldID) :
                new ObjectParameter("medicalFieldID", typeof(int));
    
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            var clinicPhoneParameter = clinicPhone != null ?
                new ObjectParameter("clinicPhone", clinicPhone) :
                new ObjectParameter("clinicPhone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_Doctor", firstNameParameter, lastNameParameter, emailParameter, passwordParameter, phoneNumberParameter, provinceParameter, cityParameter, medicalFieldIDParameter, nationalIDParameter, clinicPhoneParameter, addressParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_INS_SEL_MedicalField(string medicalField)
        {
            var medicalFieldParameter = medicalField != null ?
                new ObjectParameter("medicalField", medicalField) :
                new ObjectParameter("medicalField", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_INS_SEL_MedicalField", medicalFieldParameter);
        }
    
        public virtual ObjectResult<USP_SEL_ActiveMedicalFields_Result> USP_SEL_ActiveMedicalFields()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_ActiveMedicalFields_Result>("USP_SEL_ActiveMedicalFields");
        }
    
        public virtual ObjectResult<string> USP_SEL_Cities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_SEL_Cities");
        }
    
        public virtual ObjectResult<Nullable<int>> USP_SEL_ClinicPhone(string clinicPhone)
        {
            var clinicPhoneParameter = clinicPhone != null ?
                new ObjectParameter("clinicPhone", clinicPhone) :
                new ObjectParameter("clinicPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_SEL_ClinicPhone", clinicPhoneParameter);
        }
    
        public virtual ObjectResult<USP_SEL_Doctor_Result> USP_SEL_Doctor(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_Doctor_Result>("USP_SEL_Doctor", emailParameter);
        }
    
        public virtual ObjectResult<USP_SEL_DoctorComments_Result> USP_SEL_DoctorComments(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_DoctorComments_Result>("USP_SEL_DoctorComments", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> USP_SEL_IsDoctorActive(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("USP_SEL_IsDoctorActive", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_SEL_MedicalFieldID(string medicalField)
        {
            var medicalFieldParameter = medicalField != null ?
                new ObjectParameter("medicalField", medicalField) :
                new ObjectParameter("medicalField", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_SEL_MedicalFieldID", medicalFieldParameter);
        }
    
        public virtual ObjectResult<string> USP_SEL_MedicalFields()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_SEL_MedicalFields");
        }
    
        public virtual ObjectResult<USP_SEL_NameAndRole_Result> USP_SEL_NameAndRole(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_NameAndRole_Result>("USP_SEL_NameAndRole", emailParameter);
        }
    
        public virtual ObjectResult<USP_SEL_NotActivatedComments_Result> USP_SEL_NotActivatedComments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_NotActivatedComments_Result>("USP_SEL_NotActivatedComments");
        }
    
        public virtual ObjectResult<USP_SEL_NotActivatedDoctors_Result> USP_SEL_NotActivatedDoctors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_NotActivatedDoctors_Result>("USP_SEL_NotActivatedDoctors");
        }
    
        public virtual ObjectResult<string> USP_SEL_Provinces()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_SEL_Provinces");
        }
    
        public virtual ObjectResult<USP_SEL_SearchDoctors_Result> USP_SEL_SearchDoctors(string name, string province, string city, string medicalField)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("province", province) :
                new ObjectParameter("province", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var medicalFieldParameter = medicalField != null ?
                new ObjectParameter("medicalField", medicalField) :
                new ObjectParameter("medicalField", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_SearchDoctors_Result>("USP_SEL_SearchDoctors", nameParameter, provinceParameter, cityParameter, medicalFieldParameter);
        }
    
        public virtual ObjectResult<USP_SEL_Top6MedicalFields_Result> USP_SEL_Top6MedicalFields()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_Top6MedicalFields_Result>("USP_SEL_Top6MedicalFields");
        }
    
        public virtual int USP_UPD_ActiveComment(Nullable<int> commentID)
        {
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("commentID", commentID) :
                new ObjectParameter("commentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_ActiveComment", commentIDParameter);
        }
    
        public virtual int USP_UPD_ActiveDoctor(Nullable<int> doctorID)
        {
            var doctorIDParameter = doctorID.HasValue ?
                new ObjectParameter("doctorID", doctorID) :
                new ObjectParameter("doctorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_ActiveDoctor", doctorIDParameter);
        }
    
        public virtual int USP_UPD_Address(string email, string address)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_Address", emailParameter, addressParameter);
        }
    
        public virtual int USP_UPD_City(string email, string city)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_City", emailParameter, cityParameter);
        }
    
        public virtual int USP_UPD_ClinicPhone(string email, string clinicPhone)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var clinicPhoneParameter = clinicPhone != null ?
                new ObjectParameter("clinicPhone", clinicPhone) :
                new ObjectParameter("clinicPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_ClinicPhone", emailParameter, clinicPhoneParameter);
        }
    
        public virtual int USP_UPD_Comment(Nullable<int> commentID, string newText)
        {
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("commentID", commentID) :
                new ObjectParameter("commentID", typeof(int));
    
            var newTextParameter = newText != null ?
                new ObjectParameter("newText", newText) :
                new ObjectParameter("newText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_Comment", commentIDParameter, newTextParameter);
        }
    
        public virtual int USP_UPD_MedicalField(string email, Nullable<int> medicalFieldID, Nullable<int> newMedicalFieldID)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var medicalFieldIDParameter = medicalFieldID.HasValue ?
                new ObjectParameter("medicalFieldID", medicalFieldID) :
                new ObjectParameter("medicalFieldID", typeof(int));
    
            var newMedicalFieldIDParameter = newMedicalFieldID.HasValue ?
                new ObjectParameter("newMedicalFieldID", newMedicalFieldID) :
                new ObjectParameter("newMedicalFieldID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_MedicalField", emailParameter, medicalFieldIDParameter, newMedicalFieldIDParameter);
        }
    
        public virtual int USP_UPD_PicAddress(string email, string picAddress)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var picAddressParameter = picAddress != null ?
                new ObjectParameter("picAddress", picAddress) :
                new ObjectParameter("picAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_PicAddress", emailParameter, picAddressParameter);
        }
    
        public virtual int USP_UPD_Province(string email, string province)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("province", province) :
                new ObjectParameter("province", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_Province", emailParameter, provinceParameter);
        }
    
        public virtual int USP_UPD_Rate(string email, Nullable<byte> rate)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("rate", rate) :
                new ObjectParameter("rate", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_Rate", emailParameter, rateParameter);
        }
    
        public virtual int USP_UPD_WorkTime(string email, string workTime)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var workTimeParameter = workTime != null ?
                new ObjectParameter("workTime", workTime) :
                new ObjectParameter("workTime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_WorkTime", emailParameter, workTimeParameter);
        }
    
        public virtual int USP_INS_Person(ObjectParameter personID, string firstName, string lastName, string email, string password, string phoneNumber, string nationalID)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_Person", personID, firstNameParameter, lastNameParameter, emailParameter, passwordParameter, phoneNumberParameter, nationalIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_SEL_Email(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_SEL_Email", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_SEL_NationalID(string nationalID)
        {
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_SEL_NationalID", nationalIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_SEL_Password(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_SEL_Password", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_SEL_PhoneNumber(string phoneNumber)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_SEL_PhoneNumber", phoneNumberParameter);
        }
    
        public virtual int USP_UPD_Email(string email, string newEmail)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var newEmailParameter = newEmail != null ?
                new ObjectParameter("newEmail", newEmail) :
                new ObjectParameter("newEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_Email", emailParameter, newEmailParameter);
        }
    
        public virtual int USP_UPD_FirstName(string email, string firstName)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_FirstName", emailParameter, firstNameParameter);
        }
    
        public virtual int USP_UPD_LastName(string email, string lastName)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_LastName", emailParameter, lastNameParameter);
        }
    
        public virtual int USP_UPD_NationalID(string email, string nationalID)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_NationalID", emailParameter, nationalIDParameter);
        }
    
        public virtual int USP_UPD_Password(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_Password", emailParameter, passwordParameter);
        }
    
        public virtual int USP_UPD_PhoneNumber(string email, string phoneNumber)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPD_PhoneNumber", emailParameter, phoneNumberParameter);
        }
    }
}
